config/routes.rb
Rails.application.routes.draw do

  root 'movies#index'

  resources :movies do
    get 'show_genre', on: :member
    get 'show_director', on: :member
    get 'show_cast_member', on: :member

    resources :directors, only: :index
    resources :cast_members, only: :index
  end

  resources :genres, only: [:index, :show]
  resources :cast_members, only: [:index, :show]
  resources :directors, only: [:index, :show]

  get 'search' => 'search#search'
  post 'search' => 'search#search'

end

app/models/cast_member.rb
class CastMember < ActiveRecord::Base
  has_many :castings
  has_many :movies, through: :castings
  validates :name, uniqueness: true
  include PgSearch
  multisearchable against: :name
end

app/models/casting.rb
class Casting < ActiveRecord::Base
  belongs_to :movie
  belongs_to :cast_member
end

app/models/director.rb
class Director < ActiveRecord::Base
  has_and_belongs_to_many :movies
  validates :name, uniqueness: true
  include PgSearch
  multisearchable against: :name
end

app/models/genre.rb
class Genre < ActiveRecord::Base
  has_and_belongs_to_many :movies
  validates :name, presence: true, uniqueness: true
  include PgSearch
  multisearchable against: :name
end

app/models/movie.rb
class Movie < ActiveRecord::Base
  has_and_belongs_to_many :genres
  has_and_belongs_to_many :directors
  has_many :castings
  has_many :cast_members, through: :castings
  validates :title, presence: true
  include PgSearch
  multisearchable against: :title
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/cast_members_controller.rb
class CastMembersController < ApplicationController
  def index
    @cast_members = CastMember.all.order(:name).page(params[:page]).per(14)
  end

  def show
    @cast_member = CastMember.find(params[:id])
    @movies = @cast_member.movies.order(:title).page(params[:page]).per(12)
  end
end

app/controllers/directors_controller.rb
class DirectorsController < ApplicationController
  def index
    @directors = Director.all.order(:name).order(:name).page(params[:page]).per(14)
  end

  def show
    @director = Director.find(params[:id])
    @movies = @director.movies.order(:title).page(params[:page]).per(12)
  end
end

app/controllers/genres_controller.rb
class GenresController < ApplicationController
  def index
    @genres = Genre.all.order(:name).order(:name).page(params[:page]).per(14)
  end

  def show
    @genre = Genre.find(params[:id])
    @movies = @genre.movies.order(:title).page(params[:page]).per(12)
  end

end

app/controllers/movies_controller.rb
class MoviesController < ApplicationController
  before_action :find_movie, only: [:show, :destroy, :edit, :update, :show_genre, :show_director, :show_cast_member]

  def index
    @movies = Movie.order(:title).page(params[:page]).per(12)
  end

  def show
    @genres = @movie.genres
  end

  def new
    @movie = Movie.new
  end

  def show_genre
    @genres = @movie.genres
    render partial: 'genres/genre', collection: @genres, layout: false
  end

  def show_director
    @directors = @movie.directors
    render partial: 'directors/director', collection: @directors, layout: false
  end

  def show_cast_member
    @cast_members = @movie.cast_members
    render partial: 'cast_members/cast_member', collection: @cast_members, layout: false
  end

  def create
    @movie = Movie.new(movie_params)
    if @movie.save
      redirect_to movie_path(@movie), notice: 'Movie Created'
    else
      render :new
    end
  end

  def update
    if @movie.update_attributes(movie_params)
      redirect_to movies_path(@movie), notice: 'Movie Updated'
    else
      render :edit
    end
  end

  def destroy
    @movie.destroy
    redirect_to movies_path
  end

  private

  def find_movie
    @movie = Movie.find(params[:id])
  end

  def movie_params
    params.require(:movie).permit(:title, :year, :length, :poster)
  end
end

app/controllers/search_controller.rb
class SearchController < ApplicationController

  def search
    @pg_search_document = PgSearch.multisearch(params[:search][:query])
    @movie_results = @pg_search_document.where(searchable_type: "Movie").order(:content).page(params[:page]).per(10)
    @genre_results = @pg_search_document.where(searchable_type: "Genre").order(:content).page(params[:page]).per(10)
    @director_results = @pg_search_document.where(searchable_type: "Director").order(:content).page(params[:page]).per(10)
    @cast_results = @pg_search_document.where(searchable_type: "CastMember").order(:content).page(params[:page]).per(10)
    render file: '/search/search'
  end

  # def search1
    # @pg_search_document = PgSearch.multisearch(params[:search][:query])
    # @results = @pg_search_document.order(:content).page(params[:page]).per(10)
    # render file: '/search/search'
  # end
  # end
  #
  # def search2
  #   @movie_results = PgSearch.multisearch(params[:query]).where(searchable_type: "Movie")
  #   @genre_results = PgSearch.multisearch(params[:query]).where(searchable_type: "Genre")
  #   @director_results = PgSearch.multisearch(params[:query]).where(searchable_type: "Director")
  #   @cast_results = PgSearch.multisearch(params[:query]).where(searchable_type: "CastMember")
  # end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/cast_members_helper.rb
module CastMembersHelper
end

app/helpers/directors_helper.rb
module DirectorsHelper
end

app/helpers/genres_helper.rb
module GenresHelper
end

app/helpers/movies_helper.rb
module MoviesHelper

  # # no longer required because using kaminari gem
  # def next_page_link
  #   link_to "Next Page", movies_url(page: @page + 1) unless (@page >= (Movie.count / 12))
  # end
  #
  # def previous_page_link
  #   link_to "Previous Page", movies_url(page: @page - 1) unless (@page == 1)
  # end
end

app/helpers/search_helper.rb
module SearchHelper
end

app/views/cast_members/_cast_member.html.erb
<%= link_to cast_member.name, cast_member_path(cast_member.id) %></br>

app/views/cast_members/index.html.erb
<h1> Browse by Cast Member </h1>

<ul class="list-group">
  <% @cast_members.each do |cast_member| %>
    <%= link_to cast_member_path(cast_member) do %>
      <li class="list-group-item"><%= cast_member.name %></br>
    <% end %>
  <% end %>
</ul>

<div class = "row">
  <div class="paginate-container">
     <%= paginate(@cast_members) %>
 </div>
</div>

app/views/cast_members/show.html.erb
<h1> <%= @cast_member.name  %> </h1>

<div class = "container">
  <div class = "row">
    <div class="movie-display-container">

      <%= render partial: 'movies/movie', collection: @movies %>

    </div>
  </div>
  <div class = "row">
    <div class="paginate-container">
       <%= paginate(@movies) %>
   </div>
  </div>
</div>

app/views/directors/_director.html.erb
<%= link_to director.name, director_path(director.id) %></br>

app/views/directors/index.html.erb
<h1> Browse by Director </h1>

<ul class="list-group">
  <% @directors.each do |director| %>
    <%= link_to director_path(director) do %>
      <li class="list-group-item"><%= director.name %></br>
    <% end %>
  <% end %>
</ul>

<div class = "row">
  <div class="paginate-container">
     <%= paginate(@directors) %>
 </div>
</div>

app/views/directors/show.html.erb
<h1> <%= @director.name  %> </h1>

<div class = "container">
  <div class = "row">
    <div class="movie-display-container">

      <%= render partial: 'movies/movie', collection: @movies %>

    </div>
  </div>
  <div class = "row">
    <div class="paginate-container">
       <%= paginate(@movies) %>
   </div>
  </div>
</div>

app/views/genres/_genre.html.erb
<%= link_to genre.name, genre_path(genre.id) %></br>

app/views/genres/index.html.erb
<h1> Browse by Genre </h1>

<ul class="list-group">
  <% @genres.each do |genre| %>
    <%= link_to genre_path(genre) do %>
      <li class="list-group-item"><%= genre.name %></br>
    <% end %>
  <% end %>
</ul>

<div class = "row">
  <div class="paginate-container">
     <%= paginate(@genres) %>
 </div>
</div>

app/views/genres/show.html.erb
<h1> Browse by Genre </h1>

<ul>
  <%= @genres.each do |genre| %>
    <li><%= genre.name %></li>
    <% genre.movies.each do |genre| %>
      <%= movie.name %></br>
    <% end %>
  <% end %>
</ul>

app/views/layouts/_flash_messages.html.erb
<div class="container">
  <% flash.each do |key, value| %>
    <div class="alert alert-<%= key %>"><%= value %></div>
  <% end %>
</div>

app/views/layouts/_navbar.html.erb
<div class="navbar navbar-default navbar-static-top">
  <div class="container">
    <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-responsive-collapse">
      <span class="icon-bar"></span>
      <span class="icon-bar"></span>
      <span class="icon-bar"></span>
    </button>
    <a class="navbar-brand" href="/">Movie Database</a>
    <div class="navbar-collapse collapse navbar-responsive-collapse">
      <ul class="nav navbar-nav pull-right">
        <li>
          <%= simple_form_for 'search', url: {controller: "search", action: "search"}, html: {class: "navbar-form"} do |f|  %>
            <%= f.input 'query', label: false %>
            <%= f.button :submit, value: "Search", class: "btn-search btn-sm" %>
          <% end %>
        </li>

        <li class="dropdown">
          <%= link_to 'Browse by <b class="caret"></b>'.html_safe, request.path, :id => 'setupdrop', :'data-toggle' => 'dropdown', :class => 'dropdown-toggle' %>
          <ul class="dropdown-menu" role="menu">
            <li><%= link_to "Genre", genres_path %> </li>
            <li><%= link_to "Director", directors_path %> </li>
            <li><%= link_to "Cast Member", cast_members_path %> </li>
          </ul>
        </li>
      </ul>
    </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Movie Database</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

  <%= render 'layouts/navbar' %>
  <%= render 'layouts/flash_messages' %>

  <div class="container">

    <%= yield %>


  </div> <!-- /container -->
</body>
</html>

app/views/movies/_form.html.erb
<%= form_for @movie, :html => { :class => "form-horizontal movie" } do |f| %>

    <% if @movie.errors.any? %>
    <div id="error_expl" class="panel panel-danger">
      <div class="panel-heading">
        <h3 class="panel-title"><%= pluralize(@movie.errors.count, "error") %> prohibited this movie from being saved:</h3>
      </div>
      <div class="panel-body">
        <ul>
        <% @movie.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
        </ul>
      </div>
    </div>
  <% end %>

  <div class="control-group">
    <%= f.label :title, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :title, :class => 'form-control' %>
    </div>
    <%= error_span(@movie[:title]) %>
  </div>
  <div class="control-group">
    <%= f.label :year, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :year, :class => 'form-control' %>
    </div>
    <%= error_span(@movie[:year]) %>
  </div>
  <div class="control-group">
    <%= f.label :length, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :length, :class => 'form-control' %>
    </div>
    <%= error_span(@movie[:length]) %>
  </div>
  <div class="control-group">
    <%= f.label :poster, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :poster, :class => 'form-control' %>
    </div>
    <%= error_span(@movie[:poster]) %>
  </div>


  <%= f.submit nil, :class => 'btn btn-primary' %>
  <%= link_to t('.cancel', :default => t("helpers.links.cancel")),
            movies_path, :class => 'btn btn-default' %>

<% end %>

app/views/movies/_movie.html.erb
<div class="col-xs-6 col-sm-4 col-md-3 col-lg-2 movie-box">
  <%= link_to movie_path(movie) do  %>
    <%= image_tag movie.poster, class: "thumbnail height-100 center-block" %>
    <span class="display-title center-block"> <%= movie.title %> </span>
  <% end %>
</div>

app/views/movies/edit.html.erb
<%- model_class = Movie -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.edit', 'Edit %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

app/views/movies/index.html.erb
<div class="page-header">
  <h1><%=t '.title', :default => Movie.model_name.human.pluralize.titleize %></h1>
</div>

<div class = "container">
  <div class = "row">
    <div class="movie-display-container">

      <%= render @movies %>

    </div>
  </div>
  <div class = "row">
    <div class="paginate-container">
       <%= paginate(@movies) %>
   </div>
  </div>
</div>

app/views/movies/new.html.erb
<%- model_class = Movie -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.new', 'New %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

app/views/movies/show.html.erb
<div class="row">
  <div class="col-sm-7">
    <div class="page-header">
      <h1><%= @movie.title %></h1>
    </div>
    <dl class="dl-horizontal">
      <dt><strong> Year :</strong></dt>
      <dd><%= @movie.year %></dd>
      <dt><strong> Length:</strong></dt>
      <dd><%= @movie.length %> min</dd>
      <dt><strong> Genre(s):</strong> </br> </dt>
      <dd><%= link_to "(show)", show_genre_movie_path(@movie), id: 'show_hide_genre', remote: true %></dd>
      <dt></dt>
      <dd id="genre_output"> </dd>
      <dt><strong> Director(s):</strong> </br> </dt>
      <dd><%= link_to "(show)", show_director_movie_path(@movie), id: 'show_hide_director', remote: true %></dd>
      <dt></dt>
      <dd id="director_output"> </dd>
      <dt><strong> Cast Members(s):</strong> </br> </dt>
      <dd><%= link_to "(show)", show_cast_member_movie_path(@movie), id: 'show_hide_cast_member', remote: true %></dd>
      <dt></dt>
      <dd id="cast_member_output"> </dd>
    </dl>
  </div>
  <div class="col-sm-5">
    <%= image_tag @movie.poster, class: "height-400 center-block" %>
  </div>
</div>

<%= link_to t('.back', :default => t("helpers.links.back")),
              movies_path, :class => 'btn btn-default'  %>
<%= link_to t('.edit', :default => t("helpers.links.edit")),
              edit_movie_path(@movie), :class => 'btn btn-default' %>
<%= link_to t('.destroy', :default => t("helpers.links.destroy")),
              movie_path(@movie),
              :method => 'delete',
              :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
              :class => 'btn btn-danger' %>

app/views/search/_cast.html.erb
<li class="list-group-item">
  <%= link_to result.content, cast_member_path(result.searchable_id) %>
</li>

app/views/search/_director.html.erb
<li class="list-group-item">
  <%= link_to result.content, director_path(result.searchable_id) %>
</li>

app/views/search/_genre.html.erb
<li class="list-group-item">
  <%= link_to result.content, genre_path(result.searchable_id) %>
</li>

app/views/search/_movie.html.erb
<li class="list-group-item">
  <%= link_to result.content, movie_path(result.searchable_id) %>
</li>

app/views/search/search.html.erb
<h1> Search Results </h1>

<div class = "container">
  <div class = "row">

    <div class="col-sm-3">
      <ul class="list-group">
        <li class="list-group-item list-group-item-warning">Movies</li>
        <%= render partial: 'movie', collection: @movie_results, as: 'result' %>
      </ul>
    </div>

    <div class="col-sm-3">
      <ul class="list-group">
        <li class="list-group-item list-group-item-warning">Genres</li>
        <%= render partial: 'genre', collection: @genre_results, as: 'result' %>
      </ul>
    </div>

    <div class="col-sm-3">
      <ul class="list-group">
        <li class="list-group-item list-group-item-warning">Directors</li>
        <%= render partial: 'director', collection: @director_results, as: 'result' %>
      </ul>
    </div>

    <div class="col-sm-3">
      <ul class="list-group">
        <li class="list-group-item list-group-item-warning">Cast Members</li>
        <%= render partial: 'cast', collection: @cast_results, as: 'result' %>
      </ul>
    </div>
  </div>
</div>